### ISSUE TITLE
noDataAvailable text doesn't wrap correctly

### ISSUE THREAD

**Issue by TheLastProject** [AsteroidOS/asteroid-weather#4]
Dutch translation (to assist in testing).

Specifically https://github.com/AsteroidOS/asteroid-weather/blob/544530bffaa0381d32f99bb48269971a3897029d/main.qml#L194. As I have no ability to sync with my Android device yet, I can't test if it overflows anywhere else.

![img_20160818_013348](https://cloud.githubusercontent.com/assets/1885159/17756979/0ce72510-64e4-11e6-8405-785c420512a2.jpg)

**Comment by FlorentRevest** [comment]
This should have been fixed a few monnths ago
